package org.usfirst.frc6593.RMHRobtics.commands;

import org.usfirst.frc6593.RMHRobtics.Robot;

import edu.wpi.first.wpilibj.command.Command;

/**
 *
 */
public class SlowClimbing extends Command {

    public SlowClimbing() {
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);
    	requires(Robot.climbing);

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        }

        // Called just before this Command runs the first time
        protected void initialize() {
        }

        // Called repeatedly when this Command is scheduled to run
        protected void execute() {
        
    		Robot.climbing.startRolling(-.5);
        }

        // Make this return true when this Command no longer needs to run execute()
        protected boolean isFinished() {
            return true;
        }

        // Called once after isFinished returns true
        protected void end() {
        	//Robot.climbing.stopRolling();
        }

        // Called when another command which requires one or more of the same
        // subsystems is scheduled to run
        protected void interrupted() {
        }
    }

